### ISSUE TITLE
phpstan toevoegen aan GrumPHP

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#223]
Kan je eens checken of dat mogelijk is? Jeroen had daar toch nog wel wat errors mee gevonden dus lijkt me goed om dat bij commit te draaien

**Comment by mvanspringel** [comment]
PHPstan is not yet integrated in GrumPHP, but a [pull request (306) with the integration is open](https://github.com/phpro/grumphp/pull/306). 

PHPstan did not provide raw output, which was a problem to integrate it in GrumPHP, but [this PR in PHPstan](https://github.com/phpstan/phpstan/pull/132) is discussing this. We have to wait for an update of the PR 306 before we can use this with GrumPHP.

**Comment by tvlooy** [comment]
@mvanspringel they released it

**Comment by mvanspringel** [comment]
Since no paths can be configured in phpstan configuration files, global runs of Grumphp (grumphp run) might fail. Git specific grumphp runs (git hook & grumphp git:pre-commit) should run without any problem. Issue is open in phpstan repository, with a request to add the possibility to proivde paths in the config file, but it is unsure if it will be implemented. Since the main purpose of Grumphp (checking if individual commits are ok) is working fine, this issue will be closed when PR #253 is merged. Global runs should temporarily be avoided, until solution is found. PHP-CS-Fixer & phpstan should be run individually for now.
