### ISSUE TITLE
Docker setup doesn't work

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#403]
Tried the Docker setup, fixed 2 bugs (typo in docker-composer command and no mpm module was loaded). Now containers are running and I get this:
```
Warning: file_put_contents(/usr/local/apache2/htdocs/var/cache/dev/appDevDebugProjectContainerDeprecations.log):
    failed to open stream: Permission denied in /usr/local/apache2/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 643
```

**Comment by TomCan** [comment]
/usr/local/apache2/htdocs/ is a volume mapped to the root folder of the project on the host. No being able to write could indicate a permissions problem on the cache folder.  

My gut feeling would say that you executed console commands in your local dev environment (like cache:clear), and these commands created files with restrictive permissions so that the www-data user/group inside the php container can't write to them.

**Comment by tvlooy** [comment]
permissions on the cache and logs folders. The problem is indeed that files are owned by a different user. How should this be solved? Run the fpm service as your local user id? Is something like that possible?

**Comment by tvlooy** [comment]
needs testing
