### ISSUE TITLE
Stored XSS Vulnerability

### ISSUE THREAD

**Issue by alicanact60** [Intracto/SecretSanta#442]
Hi,
I am a security researcher and I found a stored xss vulnerability.

Steps:
1. Go to https://www.secretsantaorganizer.com
2. Fill the fields. Please look at the attachment (photo).
3. Click "Create your event!" button.
You will see xss alert.

Regards.

**Comment by alicanact60** [comment]
Photo: https://i.hizliresim.com/Ll0Rmb.jpg

PoC: https://www.secretsantaorganizer.com/created/lbn48m5mh68s88cgc4gw8kg4c0wg0oc

**Comment by tvlooy** [comment]
see #445

**Comment by tvlooy** [comment]
there is a bit of a problem. The two issues from @alicanact60 were not showing up in the interface of GIthub The issues from @mygfxx1 seem to be duplicates. The original reporter is @alicanact60 because the issue ID's are lower ...

Please send me a mail at tom.vanlooy@intracto.com so we can resolve this situation

**Comment by mygfxx1** [comment]
Because it's my another account. It was flagged. That's why I sent same reports with this account, again.

Regards.

**Comment by mygfxx1** [comment]
And I sent a mail.
