### ISSUE TITLE
Wish List/ Message

### ISSUE THREAD

**Issue by scorpyjen** [Intracto/SecretSanta#542]
Im wondering if there's a way that the host or the assistant, can help with the wish list-- some of our relatives are fossils, unfortunately, and does not understand how to use the computer.  ANd asked me to update the wish list on their behalf, and I have been unable to do so. is there a workaround for this ?

And i would love a way to send updates about the party. Theres no way to do that ?

Thanks!

**Comment by RubenHollevoet** [comment]
On the admin page you will find a 'copy personal link to clipboard' action. By using this link you can impersonate as another user and manage the wishlist on their behalf. Be aware you will also see to that persons match on this page.

There's a 'Send party updates to participants' button that will send out general party details to all participants. Unfortunately there is no way to send a custom message since this feature would attract people with bad intentions of sending out spam.
